title: "Derek’s Digital Garden" 
author: Anang Sahroni
email: "anangs972@gmail.com"
description: "The place where I rumbling around with geo, py, and other boring stuffs"
github: anangsahroni
highlighter: rouge
markdown: kramdown
parse_block_html: false
url: https://anangsahroni.github.io
permalink: blog/:title
show_drafts: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

  -
    scope:
      path: ""
      type: "posts"
    values:
      blogpost: true
      layout: post
      og-type: article
      permalink: /blog/:title
    
  -    
    scope:
      path: ""
      type: "pages"
    values:
      layout: page    

  -    
    scope:
      path: ""
      type: "no-index"
    values:
      layout: page
      no-index: true

collections:
  pages:
    output: true
  no-index:
    output: true
  unlisted:
    output: true

plugins:
  - jekyll-feed

feed: 
  categories: 
    - now
    - note
    - pygeo
    - tech
